// <auto-generated />
using System;
using GPlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GPlanner.Data.Migrations
{
    [DbContext(typeof(GPlannerDbContext))]
    partial class GPlannerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GPlanner.Core.Model.UserTask", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsArchived")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.ToTable("UserTasks", (string)null);

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            Date = new DateTime(2025, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Create slides for MAUI and ASP.NET API demonstration.",
                            IsArchived = false,
                            Priority = 5,
                            Title = "Prepare Project Defense Slides",
                            Type = 3,
                            UserId = 1
                        },
                        new
                        {
                            TaskId = 2,
                            Date = new DateTime(2025, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Replace mock data with actual HTTP GET requests to the API.",
                            IsArchived = false,
                            Priority = 4,
                            Title = "Integrate API calls into ViewModels",
                            Type = 0,
                            UserId = 1
                        },
                        new
                        {
                            TaskId = 3,
                            Date = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Check prices for holiday travel.",
                            IsArchived = false,
                            Priority = 3,
                            Title = "Book flight tickets",
                            Type = 4,
                            UserId = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
