@GPlanner.Api_HostAddress = http://localhost:5036

# Get all tasks for user 1
GET {{GPlanner.Api_HostAddress}}/api/UserTask/1
Accept: application/json

###

# Delete task with ID 5
DELETE {{GPlanner.Api_HostAddress}}/api/UserTask/5
